feat: add endpoints for Addresses
ageddesi/Mocked-API pull request #163
Opened 2022-10-05 14:59 UTC by zaibugemi

2022-10-05 15:23 UTC, zaibugemi commented
@ageddesi would you please review this PR when you have time?

2022-10-05 20:11 UTC, ageddesi requested changes
Thank you @zaibugemi for the hard work. There is just a couple of extra bits we need before we can accept the code. 👍

2022-10-05 20:11 UTC, ageddesi commented on modules/address/api/address-routes.ts
> +	app.get('/address', (req: Request, res: Response) => {
Please can you add OpenAPI comments to each endpoint please.

2022-10-05 20:11 UTC, ageddesi commented on modules/address/api/address-routes.ts
> +import { Request, Response } from 'express';
Can you add unit tests for the endpoints please

2022-10-05 20:11 UTC, ageddesi commented on modules/address/utils/getRandomAddress.ts
> +import { faker } from '@faker-js/faker';
Can you add unit tests for this please

2022-10-05 21:07 UTC, closed without merging

2022-10-06 04:39 UTC, zaibugemi commented
@ageddesi sure, let me work on your suggestions. All that work now needs to be done in a new PR, right, as this one is closed?

2022-10-06 04:41 UTC, zaibugemi commented
@ageddesi also will you also please mark this PR for `hacktoberfest` when you accept this feature?